from .models import Book

books_db: list[Book] = [
    Book(title="The Great Gatsby", author="F. Scott Fitzgerald", year=1925),
    Book(title="1984", author="George Orwell", year=1949),
    Book(title="To Kill a Mockingbird", author="Harper Lee", year=1960),
    Book(title="Pride and Prejudice", author="Jane Austen", year=1813),
    Book(title="The Catcher in the Rye", author="J.D. Salinger", year=1951),
    Book(title="Brave New World", author="Aldous Huxley", year=1932),
    Book(
        title="One Hundred Years of Solitude",
        author="Gabriel Garcia Marquez",
        year=1967,
    ),
    Book(title="Crime and Punishment", author="Fyodor Dostoevsky", year=1866),
    Book(title="Don Quixote", author="Miguel de Cervantes", year=1605),
    Book(title="Moby-Dick", author="Herman Melville", year=1851),
    Book(title="War and Peace", author="Leo Tolstoy", year=1869),
    Book(title="The Odyssey", author="Homer", year=800),
    Book(title="The Brothers Karamazov", author="Fyodor Dostoevsky", year=1880),
    Book(title="Anna Karenina", author="Leo Tolstoy", year=1877),
    Book(title="Ulysses", author="James Joyce", year=1922),
    Book(title="The Divine Comedy", author="Dante Alighieri", year=1320),
    Book(title="Middlemarch", author="George Eliot", year=1872),
    Book(title="The Lord of the Rings", author="J.R.R. Tolkien", year=1954),
    Book(title="The Hobbit", author="J.R.R. Tolkien", year=1937),
    Book(title="Jane Eyre", author="Charlotte Bronte", year=1847),
    Book(title="Wuthering Heights", author="Emily Bronte", year=1848),
    Book(title="Dune", author="Frank Herbert", year=1965),
    Book(title="Frankenstein", author="Mary Shelley", year=1818),
    Book(title="Dracula", author="Bram Stoker", year=1897),
    Book(title="Les Miserables", author="Victor Hugo", year=1862),
    Book(title="The Iliad", author="Homer", year=750),
    Book(title="The Metamorphosis", author="Franz Kafka", year=1915),
    Book(title="The Stranger", author="Albert Camus", year=1942),
    Book(title="Madame Bovary", author="Gustave Flaubert", year=1856),
    Book(title="Great Expectations", author="Charles Dickens", year=1861),
    Book(title="A Tale of Two Cities", author="Charles Dickens", year=1859),
    Book(title="The Adventures of Huckleberry Finn", author="Mark Twain", year=1884),
    Book(
        title="The Adventures of Sherlock Holmes",
        author="Arthur Conan Doyle",
        year=1892,
    ),
    Book(title="The Hound of the Baskervilles", author="Arthur Conan Doyle", year=1901),
    Book(title="The Call of the Wild", author="Jack London", year=1903),
    Book(title="White Fang", author="Jack London", year=1906),
    Book(title="Animal Farm", author="George Orwell", year=1945),
    Book(title="Slaughterhouse-Five", author="Kurt Vonnegut", year=1969),
    Book(title="Catch-22", author="Joseph Heller", year=1961),
    Book(title="The Road", author="Cormac McCarthy", year=2006),
    Book(title="To the Lighthouse", author="Virginia Woolf", year=1927),
    Book(title="Mrs. Dalloway", author="Virginia Woolf", year=1925),
    Book(title="Lolita", author="Vladimir Nabokov", year=1955),
    Book(title="On the Road", author="Jack Kerouac", year=1957),
    Book(title="The Road Not Taken", author="Robert Frost", year=1916),
    Book(title="A Little Life", author="Hanya Yanagihara", year=2015),
    Book(title="Norwegian Wood", author="Haruki Murakami", year=1987),
    Book(title="Kafka on the Shore", author="Haruki Murakami", year=2002),
    Book(title="The Wind-Up Bird Chronicle", author="Haruki Murakami", year=1994),
    Book(title="1Q84", author="Haruki Murakami", year=2009),
    Book(title="Pachinko", author="Min Jin Lee", year=2017),
    Book(title="Circe", author="Madeleine Miller", year=2018),
    Book(title="The Song of Achilles", author="Madeline Miller", year=2011),
    Book(title="The Alchemist", author="Paulo Coelho", year=1988),
    Book(title="The Night Circus", author="Erin Morgenstern", year=2011),
    Book(title="The Midnight Library", author="Matt Haig", year=2020),
    Book(title="Educated", author="Tara Westover", year=2018),
    Book(title="Project Hail Mary", author="Andy Weir", year=2021),
    Book(title="Atomic Habits", author="James Clear", year=2018),
    Book(title="The Subtle Art of Not Giving a F*ck", author="Mark Manson", year=2016),
    Book(title="Sapiens", author="Yuval Noah Harari", year=2011),
    Book(title="The Lean Startup", author="Eric Ries", year=2011),
    Book(title="Zero to One", author="Peter Thiel", year=2014),
    Book(title="Thinking, Fast and Slow", author="Daniel Kahneman", year=2011),
    Book(title="Outliers", author="Malcolm Gladwell", year=2008),
    Book(
        title="The 7 Habits of Highly Effective People",
        author="Stephen Covey",
        year=1989,
    ),
    Book(title="Man's Search for Meaning", author="Viktor Frankl", year=1946),
    Book(title="Good to Great", author="Jim Collins", year=2001),
    Book(title="The Art of War", author="Sun Tzu", year=1000),
    Book(title="Grit", author="Angela Duckworth", year=2016),
]
